### ISSUE TITLE
UP NEXT:  Will be reviewing outstanding PRs this weekend Oct 28th

### ISSUE THREAD

**Issue by PaulBratslavsky** [strapi/nextjs-corporate-starter#33]
This is a current list of the items that I am focusing on doing first.  Feel free to contribute if you like but it is not mandatory.  

- [x] Data fetching not working when in a locale that is not handled, should default to English https://github.com/strapi/nextjs-corporate-starter/issues/8
- [x] PR Review
- [x] Add SEO to Blog pages: https://github.com/strapi/nextjs-corporate-starter/issues/32
- [x] Create a deployment guide for Vercel and Strapi Cloud https://github.com/strapi/nextjs-corporate-starter/issues/22
- [x] Add mobile menu https://github.com/strapi/nextjs-corporate-starter/issues/47
- [x] Data Import not linking all media waiting for 4.10.7 this was fixed with 4.12.1 release
- [ ] Add preview mode https://github.com/strapi/nextjs-corporate-starter/issues/18 ( Backlog )
- [x] Go through open pr request ( up next )
-

**Comment by PaulBratslavsky** [comment]
This list has been completed. So will  be closing it now.
